alias k='kubectl'
alias leksnode='kubectl get nodes -o wide'
alias lekspod='kubectl get pods -A'
alias le='aws ec2 describe-instances --query "Reservations[].Instances[].{Name: Tags[?Key==\`Name\`].Value | [0], InstanceId: InstanceId, State: State.Name, PublicIP: PublicIpAddress, PrivateIP: PrivateIpAddress}" --output table'
alias lerun='aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].{Name: Tags[?Key==\`Name\`].Value | [0], InstanceId: InstanceId, PublicIP: PublicIpAddress}" --output table'
alias ls3='aws s3 ls'
alias ls3f='aws s3 ls s3://'
alias lvpc='aws ec2 describe-vpcs --query "Vpcs[].{Name: Tags[?Key==\`Name\`].Value | [0], VpcId: VpcId, CidrBlock: CidrBlock, IsDefault: IsDefault}" --output table'
alias lsub='aws ec2 describe-subnets --query "Subnets[].{Name: Tags[?Key==\`Name\`].Value | [0], SubnetId: SubnetId, VpcId: VpcId, CidrBlock: CidrBlock, AZ: AvailabilityZone}" --output table'
alias luser='aws iam list-users --query "Users[].[UserName,UserId,CreateDate]" --output table'
alias lrole='aws iam list-roles --query "Roles[].[RoleName,CreateDate]" --output table'
echo "🚀 Shortcuts loaded! (k, le, ls3, lvpc, etc. are ready to use)"
